version: "3.5"

services:
  db:
    image: mariadb:latest
    container_name: app_db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app_backend
  phpmyadmin:
    container_name: app_phpmyadmin
    restart: "always"
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    networks:
      - app_backend
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_php_fpm
    restart: always
    working_dir: ${NGINGX_ROOT}
    depends_on:
      - db
    expose:
      - "9000"
    networks:
      - app_backend
    volumes:
        - ./:${NGINGX_ROOT}
  nginx:
    image: nginx:latest
    container_name: app_nginx
    restart: always
    working_dir: ${NGINGX_ROOT}
    depends_on:
      - web
    networks:
      - app_backend
    ports:
      - "80:80"
    volumes:
      - ./:${NGINGX_ROOT}
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:latest
    container_name: app_redis
    networks:
      - app_backend
    ports:
      - "6382:6379"
  composer:
    image: composer:latest
    working_dir: ${NGINGX_ROOT}
    command: install
    volumes:
      - ./:${NGINGX_ROOT}
  node:
    build:
      context: .
      dockerfile: ./docker/npm/Dockerfile
    container_name: app_npm
    working_dir: ${NGINGX_ROOT}
    volumes:
      - ./:${NGINGX_ROOT}
networks:
  app_backend:
    driver: bridge
